#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Convert this sweep's metrics CSV into the blog-28 plot-script schema.

The plot scripts expect ``combo,lpips_mean7,gen_sec_mean`` with combo shaped
``<QUANT>_s<0|1>_t<NNN>_d<NNN>``, where ``d000`` marks the dense (no
Skip-Softmax) anchor for that family.  This sweep names combos differently
(``TRTLLM_WFP8STATIC_ABF16_t070_d094``), so the mapping is made explicit here
rather than by string-munging inside the plot code.

The blog uses the published static FP8 per-tensor and NVFP4 checkpoints. Dynamic
quantization families present in the source sweep are omitted from the output.

  to_blog28_csv.py SWEEP_METRICS_CSV OUT_CSV
"""

import csv
import sys

# Source family -> (blog quantization key, SAGE flag).
FAMILY_MAP = {
    "TRTLLM_WBF16_ABF16": ("BF16", 0),
    "TRTLLM_WBF16_SAGE_QKINT8_PVFP8": ("BF16", 1),
    "TRTLLM_WFP8STATIC_ABF16": ("FP8_STATIC", 0),
    "TRTLLM_WFP8STATIC_SAGE_QKINT8_PVFP8": ("FP8_STATIC", 1),
    "TRTLLM_WNVFP4STATIC_ABF16": ("NVFP4_STATIC", 0),
    "TRTLLM_WNVFP4STATIC_SAGE_QKINT8_PVFP8": ("NVFP4_STATIC", 1),
}

# The dense anchor is target-independent; the plot scripts store it at t075.
DENSE_TARGET = "075"
EXCLUDED = {
    "TRTLLM_WFP8_SAGE_QKINT8_PVFP8",
    "TRTLLM_WFP8_ABF16",
    "TRTLLM_WNVFP4_ABF16",
    "TRTLLM_WNVFP4_SAGE_QKINT8_PVFP8",
}


def main() -> None:
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise SystemExit(f"{src} is empty")
    # Accuracy reference is compiled BF16 dense -- the SAME configuration the
    # speedup baseline uses, so both axes share one reference and the BF16 dense
    # row is 1.000x / 0.0000 by construction.  Referencing latency to compiled
    # BF16 but quality to eager BF16 puts the compile-vs-eager delta (a property
    # of the baseline, not of any candidate) on the quality axis.
    # Fail rather than fall back: a silent reference swap is invisible in the plot.
    lp = "lpips_vs_compiled_bf16_mean7"
    if lp not in rows[0]:
        raise SystemExit(
            f"{src} lacks {lp}; use the main collector CSV (sweep_metrics9.csv)."
        )
    if lp not in rows[0] or "gen_sec_mean" not in rows[0]:
        raise SystemExit(f"{src} lacks LPIPS/latency columns: {list(rows[0])}")

    out, seen, dropped = [], set(), []
    for row in rows:
        combo = row["combo"]
        if combo.startswith("EAGER"):
            continue
        if any(combo.startswith(x) for x in EXCLUDED):
            dropped.append(combo)
            continue
        if combo.endswith("_dense"):
            family, target, disabled = combo[: -len("_dense")], DENSE_TARGET, "000"
        else:
            family, target_token, disabled_token = combo.rsplit("_", 2)
            target, disabled = target_token.removeprefix("t"), disabled_token.removeprefix("d")
        if family not in FAMILY_MAP:
            raise SystemExit(f"unmapped family: {family} (from {combo})")
        quant, sage = FAMILY_MAP[family]
        name = f"{quant}_s{sage}_t{target}_d{disabled}"
        if name in seen:
            raise SystemExit(f"duplicate mapped combo {name} (from {combo})")
        seen.add(name)
        out.append(
            {
                "combo": name,
                "n_prompts": 7,
                "lpips_mean7": f"{float(row[lp]):.6f}",
                "gen_sec_mean": f"{float(row['gen_sec_mean']):.3f}",
            }
        )

    out.sort(key=lambda r: r["combo"])
    with open(dst, "w", newline="") as handle:
        handle.write(
            "# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. "
            "All rights reserved.\n"
            "# SPDX-License-Identifier: Apache-2.0\n"
            "# Generated by to_blog28_csv.py from this sweep's metrics CSV.\n"
        )
        writer = csv.DictWriter(
            handle, fieldnames=["combo", "n_prompts", "lpips_mean7", "gen_sec_mean"]
        )
        writer.writeheader()
        writer.writerows(out)
    if dropped:
        print(
            f"EXCLUDED {len(dropped)} rows by request: "
            f"{sorted({c.rsplit('_', 2)[0] for c in dropped})}"
        )
    fams = sorted({r["combo"].rsplit("_", 2)[0] for r in out})
    print(f"WROTE {dst}: {len(out)} rows, families={fams}")
    for f in fams:
        if f"{f}_t075_d000" not in seen:
            print(f"  NOTE: {f} has no dense (d000) anchor")


if __name__ == "__main__":
    main()
